name: Weather_app

trigger:
    - branch1

stages:
    - stage: Build
      jobs:
        - job: build_and_test
          displayName: Build and Test
          steps:
              - task: UsePythonVersion@0
                inputs:
                    versionSpec: 3.11
                displayName: Use Python 3.11
              - script: |
                    python -m venv .venv
                    source .venv/bin/activate
                    pip install --upgrade pip
                    pip install -r requirements.txt
                displayName: 'Installing dependencies'    