# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  ACR_LOGIN_SERVER: 'devopslearningacr.azurecr.io'
  IMAGE_NAME: 'weather-app'
  IMAGE_TAG: 'latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'
  displayName: 'Use Python 3.11'

- script: |
    python -m venv .venv
    source .venv/bin/activate
    pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Installing dependencies'

- script: |
    echo "Running script..."
    source .venv/bin/activate
    python main.py
  displayName: 'Run main.py'
  env:
    API_KEY: $(API_KEY)

- script: |
    echo "Running tests..."
    source .venv/bin/activate
    pytest
  displayName: "Run pytest"
  env:
    API_KEY: $(API_KEY)

#--------DOCKER-------------
- task: Docker@2
  displayName: 'Log in to ACR'
  inputs:
    command: login
    containerRegistry: 'mg_conn'

- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    command: build
    Dockerfile: 'Dockerfile'
    repository: 'weather-app'
    tags: |
      latest

- task: Docker@2
  displayName: 'Push Docker image'
  inputs:
    command: push
    repository: 'weather-app'
    tags: |
      latest