name: Weather_app

trigger:
    - branch1

stages:
    - stage: Build_and_Test
      displayName: Build and Test
      jobs:
        - job: build_and_test
          displayName: Build and Test
          steps:
              - task: UsePythonVersion@0
                inputs:
                    versionSpec: 3.11
                displayName: Use Python 3.11
              - script: |
                    python -m venv .venv
                    source .venv/bin/activate
                    pip install --upgrade pip
                    pip install -r requirements.txt
                displayName: 'Installing dependencies'    
              - script: |
                  echo "Running script..."
                  source .venv/bin/activate
                  python main.py
                displayName: 'Run main.py'
                env:
                  API_KEY: $(API_KEY)
              - script: |
                  echo "Running tests..."
                  source .venv/bin/activate
                  pytest
                displayName: "Run pytest"
                env:
                  API_KEY: $(API_KEY)  